Repository apple/servicetalk, pull requests merged in 2021-12, with the labels that each got.

#1957 Transportevents offloading
  servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ReservableRequestConcurrencyControllers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Processors.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingStrategyInfluencer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToOffloadedStreamingHttpService.java
  servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
  servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategy.java
Labels: enhancement, API

#1976 Cleanup LoadBalancer APIs
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpLoadBalancerFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpLoadBalancerFactory.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AutoRetryTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-loadbalancer/build.gradle
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/EagerRoundRobinLoadBalancerTest.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Labels: breaking-change

#1984 Remove `subscribeShareContext` method
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Labels: breaking-change

#1982 Remove default impl from `ConnectionObserver`
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
Labels: breaking-change

#1981 Remove deprecated `AbstractRetryingFilterBuilder` build methods
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
Labels: breaking-change

#1980 Remove deprecated `HttpClients` factories for proxy
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Labels: breaking-change

#1983 `publishOn/subscribeOn` take `io.servicetalk.concurrent.Executor`
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java
Labels: breaking-change

#1972 Introduce `TimeSource` in `Executor`
  servicetalk-concurrent-api-test/src/main/java/io/servicetalk/concurrent/api/test/TimeSource.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ContextPreservingStExecutor.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DelegatingExecutor.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TimeoutPublisher.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/completable/TimeoutCompletableTest.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/publisher/TimeoutPublisherTest.java
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
  servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/Executor.java
  servicetalk-concurrent/src/main/java/io/servicetalk/concurrent/TimeSource.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/MinTtlCache.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseTimeoutTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilter.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutFromRequest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilter.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutHttpServiceFilter.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpRequesterFilterTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/TimeoutHttpServiceFilterTest.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/EventLoopAwareNettyIoExecutor.java
Labels: breaking-change

#1977 Fix client expected strategies regression
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingToStreamingService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingToStreamingService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultStreamingStrategyInfluencer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpApiConversions.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ServiceToStreamingService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingStreamingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingHttpConnection.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingStreamingHttpConnection.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToHttpConnection.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/FilterableClientToClient.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
Labels: bug

#1985 `StatelessTrailersTransformer`: Object -> Void state
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StatelessTrailersTransformer.java
Labels: breaking-change

#1989 Deprecate and replace `noOffloadsStrategy()`
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyConfigurationFailuresTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientValidatesContentTypeTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/AbstractBlockingStreamingHttpRequesterTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingHttpClientTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingHttpConnectionTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyMergeTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategiesTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractEchoServerBasedHttpRequesterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthStrategyInfluencerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpAuthConnectionFactoryClientTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientBuilderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientOverrideOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionEmptyPayloadTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpStreamingClientOverrideOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTestExecutionStrategy.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RedirectingClientAndConnectionFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerGracefulConnectionClosureHandlingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java
  servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategyUtils.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractResourceTest.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyTest.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/MixedModeResourceTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpServerOverrideOffloadingTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
Labels: API

#1948 Configurable offloading for async close
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionContext.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/FilterableStreamingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
  servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
  servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategy.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultConnectExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultExecutionContext.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SpecialExecutionStrategy.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ChannelSet.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyServerContext.java
Labels: enhancement

#1991 Update junit 5.8.1 -> 5.8.2, junit-platform 1.8.0 -> 1.8.2
  gradle.properties
Labels: dependencies, technical debt

#1992 Update protobuf 3.18.1 -> 3.19.1
  gradle.properties
Labels: dependencies, technical debt

#1995 Update protobuf-gradle-plugin 0.8.17 -> 0.8.18
  gradle.properties
Labels: dependencies, technical debt

#1997 Upgrade build PMD 6.38.0 → 6.41.0
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Labels: dependencies, technical debt

#1996 Upgrade build Checkstyle 9.0 → 9.2
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Labels: dependencies, technical debt

#1988 Add weight factor to the load balanced addresses
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancedAddress.java
Labels: API

#1990 Introduce `HttpServerContext` and `GrpcServerContext`
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerContext.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceFactory.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
Labels: breaking-change

#1979 Fail to start without native transport
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NativeTransportUtils.java
Labels: breaking-change

#1998 Remove non-relevant javadoc from `MultiAddressHttpClientBuilder#followRedirects`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
Labels: technical debt

#1999 `DefaultMultiAddressUrlHttpClientBuilder`: remove unused `unresolvedAddressToHostFunction`
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
Labels: technical debt

#1986 Convert `BlockingStreamingHttpServerResponse` to an interface
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpServerResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultBlockingStreamingHttpServerResponse.java
Labels: breaking-change

#2017 Close can be observed on test executor thread
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
Labels: flaky tests

#2012 `TransportObserver#onNewConnection` give visibility into addresses
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SecurityHandshakeObserverTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpConnector.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverErrorsTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/SecureTcpTransportObserverTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverErrorsTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpTransportObserverTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportObserver.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
Labels: API

#2013 `Read/WriteObserver`: give users visibility into items
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTransportObserverTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/Flush.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/WriteStreamSubscriber.java
Labels: API

#2014 Clean up Read/WriteObserver after #2013
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
Labels: breaking-change

#2015 Clean up TransportObserver after #2012
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverAsyncContextTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/BiTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/CatchAllTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/NoopTransportObserver.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/TransportObserver.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NoopTransportObserver.java
Labels: API, breaking-change

#2018 Fix sharing issue with Retrying requests filter factory
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/AutoRetryStrategyProvider.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
Labels: bug, enhancement

#2019 Retry unification deprecations removal
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/AutoRetryStrategyProvider.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultAutoRetryStrategyProvider.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancerReadySubscriber.java
  servicetalk-examples/http/service-composition/src/main/java/io/servicetalk/examples/http/service/composition/GatewayServer.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/GrpcLifecycleObserverRequesterFilter.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AutoRetryFilter.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpLifecycleObserverRequesterFilter.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AutoRetryTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionAcceptingNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RetryingHttpRequesterFilter.java
Labels: breaking-change

#2030 Upgrade Log4J 2.16.0 to 2.17.0
  gradle.properties
Labels: dependencies

#2031 Prevent retry logic modifications through the builder
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
Labels: bug
