Repository apple/servicetalk, pull requests merged in 2021-10, with the labels that each got.

#1792 Enhance `RedirectingHttpRequesterFilter`: redirect headers and message body
  servicetalk-examples/docs/modules/ROOT/pages/http/index.adoc
  servicetalk-examples/http/redirects/build.gradle
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/ManualRedirectClient.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/MultiAddressUrlRedirectClient.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/RedirectWithStateUrlClient.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/RedirectingServer.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/SimpleRedirectUrlClient.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/SingleAddressRedirectClient.java
  servicetalk-examples/http/redirects/src/main/java/io/servicetalk/examples/http/redirects/package-info.java
  servicetalk-http-api/gradle/spotbugs/main-exclusions.xml
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMethod.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfig.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/RedirectConfigBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RedirectingClientAndConnectionFilterTest.java
  servicetalk-http-utils/build.gradle
  servicetalk-http-utils/gradle/spotbugs/main-exclusions.xml
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectSingle.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilter.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RetryingHttpRequesterFilter.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultHostAndPort.java
Labels: enhancement

#1864 `japicmp.sh`: skip jdkflow on JDK8 and adjust error msg format
  scripts/japicmp.sh
Labels: bug

#1862 Clean up deprecated API after changes for redirects in #1792
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilter.java
Labels: breaking-change

#1923 Enhance GrpcStatus.fromCodeValue static factories to include actual status code when it maps to UNKNOWN
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcStatus.java
  servicetalk-grpc-api/test/java/io/servicetalk/grpc/api/GrpcStatusTest.java
Labels: enhancement
