Repository apple/servicetalk, pull requests merged in 2021-08, with the labels that each got.

#1720 Deprecate `HttpExecutionStrategy.invokeService`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
Labels: API

#1723 Simplify conditional offloading
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java
Labels: API, breaking-change

#1710 Add support for nonOffloading HTTP Server Filters
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ClearAsyncContextHttpServiceFilter.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DelegatingHttpServiceContext.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/NoOffloadsHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/OffloadingFilter.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/BlockingStreamingToStreamingServiceTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyMergeTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
  servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerFilterOrderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InsufficientlySizedExecutorHttpTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/InvokingThreadsRecorder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NoOffloadsStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
  servicetalk-http-router-predicate/src/main/java/io/servicetalk/http/router/predicate/InOrderRouter.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilterTest.java
Labels: enhancement, API

#1728 Safer offloading handleSubscribe invocation
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java
Labels: bug

#1721 MultiAddressHttpClientBuilder API cleanup
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseHttpBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ExecutionContextAwareHttpBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuildFinalizer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientFilterFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerAwareConversions.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientFilterFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
Labels: breaking-change

#1731 Cleanup of PartitionedHttpClientBuilder
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
Labels: breaking-change

#1737 javadoc fixes for JDK 16 compatibility
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-internal/src/main/java/io/servicetalk/concurrent/internal/SignalOffloader.java
Labels: docs, technical debt

#1743 Simplify API hierarchy of HTTP and gRPC client builders
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BaseGrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ExecutionContextAwareHttpBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuildFinalizer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
Labels: breaking-change

#1738 Deprecate `IoExecutor` create w/ `ThreadFactory`
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerMultipleRequestsTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpUdsTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpsProxyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslProvidersTest.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractJerseyStreamingHttpServiceTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoThreadFactory.java
  servicetalk-transport-netty-internal/gradle/spotbugs/main-exclusions.xml
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/GlobalExecutionContext.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/IoThreadFactory.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoExecutors.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoThreadFactory.java
  servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextExtension.java
  servicetalk-transport-netty-internal/src/testFixtures/java/io/servicetalk/transport/netty/internal/ExecutionContextRule.java
  servicetalk-transport-netty/src/main/java/io/servicetalk/transport/netty/NettyIoExecutors.java
Labels: API

#1762 Migrate `servicetalk-loadbalancer` module tests to jUnit5
  servicetalk-loadbalancer/build.gradle
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/EagerRoundRobinLoadBalancerTest.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/LingeringRoundRobinLoadBalancerTest.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Labels: technical debt

#1756 Deprecate syncUninterruptibly() and awaitRequestNUninterruptibly() in tests
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSubscription.java
  servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyChannelContentCodec.java
  servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyCompressionSerializer.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2ConcurrencyControllerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkContentEncodingCompatibilityTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServiceTalkToNettyContentCodingCompatibilityTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
  servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpClient.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/DefaultNettyConnectionTest.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/RequestResponseCloseHandlerTest.java
Labels: technical debt

#1752 Add `EnforceSequentialModeRequesterFilter` for `http-utils` module
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FullDuplexAndSequentialModeTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/EnforceSequentialModeRequesterFilter.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/EnforceSequentialModeRequesterFilterTest.java
Labels: enhancement

#1757 Allow users enable validation for header values
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeaders.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpSetCookie.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpHeadersFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiMap.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpHeadersTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpSetCookiesTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/StreamingHttpPayloadHolderTest.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ClientDuplexHandler.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ToStH1ServerDuplexHandler.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyH2HeadersToHttpHeaders.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbsoluteAddressHttpRequesterFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentHeadersTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ContentLengthTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpRequestEncoderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpResponseEncoderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/IllegalHeaderValueTest.java
Labels: enhancement, API

#1765 Update gradlew wrapper 7.1.1 -> 7.2
  docs/generation/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: technical debt

#1767 ZipkinPublisher remove unnecessary data
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpanBuilder.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTracer.java
  servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java
Labels: performance

#1771 Update checkstyle 8.43 -> 9.0
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/AbstractRetryingFilterBuilder.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSubscription.java
  servicetalk-data-jackson-jersey/src/main/java/io/servicetalk/data/jackson/jersey/ServiceTalkJacksonSerializerFeature.java
  servicetalk-encoding-api-internal/src/main/java/io/servicetalk/encoding/api/internal/HeaderUtils.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/Identity.java
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientCallFactory.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientFactory.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceContext.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpServerResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultClassHttpDeserializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultClassHttpSerializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpHeadersFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultSizeAwareClassHttpSerializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultSizeAwareTypeHttpSerializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultTypeHttpDeserializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultTypeHttpSerializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpDeserializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializationProviders.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpSerializer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionHttpClientBuilderConfigurator.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2HeadersFactory.java
  servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/Serializer.java
  servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/StreamingDeserializer.java
  servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/StreamingSerializer.java
  servicetalk-serialization-api/src/main/java/io/servicetalk/serialization/api/TypeHolder.java
Labels: dependencies, technical debt

#1769 Update PMD 6.35.0 -> 6.38.0
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Labels: dependencies, technical debt

#1766 Adds stack capture to OffloadingTest
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/AbstractCompletableOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CaptureReferences.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublisherOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/AbstractSingleOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java
Labels: flaky tests

#1773 Update to use PMD PrimitiveWrapperInstantiation rule
  servicetalk-gradle-plugin-internal/src/main/resources/io/servicetalk/gradle/plugin/internal/pmd/basic.xml
Labels: technical debt

#1774 Ignore spotbugs encapsulation warnings for gradle
  servicetalk-gradle-plugin-internal/gradle/spotbugs/main-exclusions.xml
Labels: bug
