Repository apple/servicetalk, pull requests merged in 2021-07, with the labels that each got.

#1648 Deprecate publishAndSubscribeOn
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Labels: API

#1649 Remove publishAndSubscribeOn
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/ExecutorThrowsTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/ReduceOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/CompletableStepVerifierTest.java
  servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/PublisherStepVerifierTest.java
  servicetalk-concurrent-api-test/src/test/java/io/servicetalk/concurrent/api/test/SingleStepVerifierTest.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapMergeTest.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/CompletionStageAsyncContextTest.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletionStageTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletablePublishAndSubscribeOnTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherPublishAndSubscribeOnTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SinglePublishAndSubscribeOnTckTest.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/FlushWithExecutorTest.java
Labels: API, breaking-change

#1656 Fixes issues with GRPC Examples documentation
  servicetalk-examples/docs/modules/ROOT/pages/grpc/index.adoc
Labels: docs

#1657 Remove SNAPSHOT from validation path for docs
  docs/generation/gradle/validateSite.gradle
Labels: docs

#1661 Add `awaitSubscribed()` to test async sources
  servicetalk-concurrent-api/build.gradle
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestCompletable.java
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestPublisher.java
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestSingle.java
  servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
  servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/TestPublisherSubscriber.java
Labels: API, enhancement

#1660 Migrate servicetalk-grpc-* tests to junit5
  servicetalk-grpc-api/build.gradle
  servicetalk-grpc-netty/build.gradle
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/api/CatchAllHttpServiceFilterTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ClosureTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyConfigurationFailuresTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientValidatesContentTypeTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcRouterConfigurationTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcServiceContextProtocolTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcUdsTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/HttpResponseUponGrpcRequestTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/PendingStreamingClosureTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/SingleRequestOrResponseApiTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/TrailersOnlyErrorTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/protoc/GeneratorTest.java
  servicetalk-grpc-protobuf/build.gradle
  servicetalk-grpc-protobuf/src/test/java/io/servicetalk/grpc/protobuf/ProtoDeserializerTest.java
  servicetalk-grpc-protoc/build.gradle
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/StringUtilsTest.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictMultiService.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictRpc.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictService.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestMulti.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestSingle.java
Labels: technical debt

#1662 Enforce correct AsyncContext use and name "thread"
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
Labels: enhancement

#1659 Migrate servicetalk-http-* tests to junit5
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
  servicetalk-http-router-predicate/build.gradle
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/BaseHttpPredicateRouterBuilderTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/DefaultFallbackServiceTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderCookieTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderHeaderTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderQueryTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpPredicateRouterBuilderTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpServerOverrideOffloadingTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
  servicetalk-http-security-jersey/build.gradle
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/AbstractBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/BasicAuthSecurityContextFiltersTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/NameBindingBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/RoleProtectedBasicAuthSecurityContextFilterTest.java
  servicetalk-http-utils/build.gradle
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/AbstractTimeoutHttpFilterTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/BeforeFinallyHttpOperatorTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/HttpRequestUriUtilsTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RedirectingHttpRequesterFilterTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/RequestTargetEncoderHttpServiceFilterTest.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilterTest.java
Labels: technical debt

#1666 Specify PITest version in `Versions.groovy`
  gradle.properties
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Labels: bug

#1667 `ClientEffectiveStrategyTest` and `ServerEffectiveStrategyTest` cleanups
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
Labels: technical debt

#1669 Deprecate OpenTracing APIs that will be removed later through a breaking-api release.
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpan.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContext.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceState.java
Labels: API

#1675 Permit copy for `TestExecutor` `AsyncContextMap`
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
Labels: bug

#1676 SequentialSubscription reentry bug fix
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/SequentialSubscription.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SequentialSubscriptionTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherRepeatTckTest.java
Labels: bug

#1681 Remove unused imports from examples
  servicetalk-examples/grpc/routeguide/src/main/java/io/servicetalk/examples/grpc/routeguide/FeaturesFinder.java
  servicetalk-examples/http/jaxrs/src/main/java/io/servicetalk/examples/http/jaxrs/HelloWorldJaxRsApplication.java
Labels: good first issue, technical debt

#1640 Fix B3 sampling API to support missing values
  servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/AbstractTracingHttpFilter.java
  servicetalk-opentracing-http/src/main/java/io/servicetalk/opentracing/http/TracingHttpHeadersFormatter.java
  servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpRequesterFilterTest.java
  servicetalk-opentracing-http/src/test/java/io/servicetalk/opentracing/http/TracingHttpServiceFilterTest.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpan.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContext.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemorySpanContextFormat.java
  servicetalk-opentracing-inmemory-api/src/main/java/io/servicetalk/opentracing/inmemory/api/InMemoryTraceState.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemorySpan.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/AbstractInMemoryTracer.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemorySpanContext.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTraceState.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTracer.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/SampledInMemorySpan.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/SingleLineFormatter.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/SingleLineValue.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/TextMapFormatter.java
  servicetalk-opentracing-inmemory/src/main/java/io/servicetalk/opentracing/inmemory/UnsampledInMemorySpan.java
  servicetalk-opentracing-inmemory/src/test/java/io/servicetalk/opentracing/inmemory/DefaultInMemoryTracerTest.java
  servicetalk-opentracing-internal/src/main/java/io/servicetalk/opentracing/internal/TracingIdUtils.java
  servicetalk-opentracing-log4j2/build.gradle
  servicetalk-opentracing-log4j2/src/main/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMap.java
  servicetalk-opentracing-log4j2/src/test/java/io/servicetalk/opentracing/log4j2/ServiceTalkTracingThreadContextMapTest.java
  servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/ZipkinPublisher.java
Labels: breaking-change

#1588 Allow JUnit 5 tests to execute concurrently
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/single/SingleToCompletionStageTest.java
  servicetalk-test-resources/src/main/resources/junit-platform.properties
Labels: flaky tests

#1699 TestExecutor Runnable preserve AsyncContextMap
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
Labels: bug

#1689 Conditional offload `publishOn` & `subscribeOn`
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/AbstractCompletableOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/AbstractOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/internal/CaptureReferences.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/AbstractPublisherOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/OffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/AbstractSingleOffloadingTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/OffloadingTest.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractAsynchronousCompletableOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractAsynchronousPublisherOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractAsynchronousSingleOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncCompletableOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncPublisherOperator.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/TaskBasedAsyncSingleOperator.java
Labels: API, enhancement
