Repository apple/servicetalk, pull requests merged in 2021-11, with the labels that each got.

#1927 Remove deprecated methods from AwaitUtils
  servicetalk-concurrent-test-internal/src/main/java/io/servicetalk/concurrent/test/internal/AwaitUtils.java
Labels: breaking-change

#1930 Remove `grpc` and `http` modules from BOM
  servicetalk-bom/build.gradle
Labels: bug

#1922 Remove unused exception types
  servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/MaxRequestLimitExceededRejectedSubscribeException.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionClosedException.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/MaxRequestLimitExceededException.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/InvalidRedirectException.java
Labels: breaking-change

#1938 RoundRobinLoadBalancer: reduce number of operators in health check chain
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
  servicetalk-loadbalancer/src/test/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerTest.java
Labels: performance

#1931 Deprecate `ServiceDiscoveryRetryStrategy`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultServiceDiscoveryRetryStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ServiceDiscoveryRetryStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
Labels: API

#1950 Update build to Gradle 7.3
  docs/generation/gradle/wrapper/gradle-wrapper.properties
  docs/generation/gradlew
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: technical debt

#1952 Restore `HttpExecutionContextBuilder` returns
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpExecutionContextBuilder.java
Labels: bug

#1953 Update to PITest 1.7.3 and matching plugins
  gradle.properties
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
Labels: technical debt

#1924 Adjust parent types for exceptions
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionRejectedException.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/LoadBalancer.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/NoAvailableHostException.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/partition/DuplicateAttributeException.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RepeatStrategies.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/MessageEncodingException.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/UnsupportedHttpChunkException.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ResponseTimeoutTest.java
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Labels: breaking-change

#1955 Multi-address client: throw `MalformedURLException` instead of `IllegalArgumentException`
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MultiAddressUrlHttpClientTest.java
Labels: breaking-change

#1954 Minor `ExecutionStrategy` cleanups
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategy.java
  servicetalk-http-api/src/testFixtures/java/io/servicetalk/http/api/DelegatingHttpExecutionStrategy.java
  servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SpecialExecutionStrategy.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/AbstractSslCloseNotifyAlertHandlingTest.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NoopExecutionStrategy.java
Labels: bug

#1959 Clean up `AsyncContext` API
  docs/modules/ROOT/pages/performance.adoc
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContext.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextMap.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextMapHolder.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextMapThreadLocal.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextMapToContextMapAdapter.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AsyncContextProvider.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ConcurrentContextMap.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/CopyOnWriteContextMap.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultAsyncContextProvider.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/NoopAsyncContextProvider.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AsyncContextDisableNewTest.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/AsyncContextDisableTest.java
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/TestExecutor.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
  servicetalk-grpc-internal/src/main/java/io/servicetalk/grpc/internal/DeadlineUtils.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceAsyncContextDeprecatedTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceAsyncContextMigrationTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceAsyncContextNewTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BlockingStreamingHttpServiceAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextDeprecatedTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextMigrationTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextNewTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextDeprecatedTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextMigrationTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextNewTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java
  servicetalk-http-security-jersey/src/main/java/io/servicetalk/http/security/auth/basic/jersey/AbstractBasicAuthSecurityContextFilter.java
  servicetalk-http-security-jersey/src/main/java/io/servicetalk/http/security/auth/basic/jersey/BasicAuthSecurityContextFilters.java
  servicetalk-http-security-jersey/src/main/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilter.java
  servicetalk-http-security-jersey/src/main/java/io/servicetalk/http/security/auth/basic/jersey/NameBindingBasicAuthSecurityContextFilter.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/AbstractBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/GlobalBindingBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/NameBindingBasicAuthSecurityContextFilterTest.java
  servicetalk-http-security-jersey/src/test/java/io/servicetalk/http/security/auth/basic/jersey/RoleProtectedBasicAuthSecurityContextFilterTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilter.java
  servicetalk-http-utils/src/test/java/io/servicetalk/http/utils/auth/BasicAuthHttpServiceFilterTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/IoThreadFactory.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyIoThreadFactory.java
Labels: API, breaking-change

#1961 Cleanup default methods from `HttpMetaData`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingStreamingHttpResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpMetaData.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpRequestMetaData.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponse.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpResponseMetaData.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpRequest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpResponse.java
Labels: breaking-change

#1964 Restore `ServiceDiscovererUtils` methods and mark them as deprecated
  servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/ServiceDiscovererUtils.java
Labels: API

#1965 Restore `BaseSingleAddressHttpClientBuilder#retryServiceDiscoveryErrors`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
Labels: API

#1962 Removing deprecated `ServiceDiscovererEvent` methods
  servicetalk-benchmarks/src/jmh/java/io/servicetalk/benchmark/loadbalancer/RoundRobinLoadBalancerSDEventsBenchmark.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/DefaultServiceDiscovererEvent.java
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/ServiceDiscovererEvent.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DefaultDnsClient.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/DnsServiceDiscovererObserver.java
  servicetalk-dns-discovery-netty/src/main/java/io/servicetalk/dns/discovery/netty/ServiceDiscovererUtils.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientBuilderTest.java
Labels: breaking-change

#1921 `ConnectionAcceptor` `ConnectionFactory` offloading control
  servicetalk-client-api/src/main/java/io/servicetalk/client/api/ConnectionFactoryFilter.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AlpnLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DeferredServerChannelBinder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2LBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ServerParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpConnection.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/PipelinedLBHttpConnectionFactory.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionAcceptorOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionFactoryOffloadingTest.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerBinder.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/AbstractTcpServerTest.java
  servicetalk-tcp-netty-internal/src/test/java/io/servicetalk/tcp/netty/internal/TcpServerBinderConnectionAcceptorTest.java
  servicetalk-tcp-netty-internal/src/testFixtures/java/io/servicetalk/tcp/netty/internal/TcpServer.java
  servicetalk-transport-api/build.gradle
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ConnectionAcceptorFactory.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/DefaultConnectExecutionStrategy.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ExecutionStrategyInfluencer.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/InfluencerConnectionAcceptor.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/InfluencerConnectionAcceptorTest.java
Labels: enhancement, API
