Repository apple/servicetalk, pull requests merged in 2021-06, with the labels that each got.

#1590 Upgrade to Gradle 7.0.2
  gradle/wrapper/gradle-wrapper.properties
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ProjectUtils.groovy
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkCorePlugin.groovy
Labels: dependencies

#1561 Allow using `null` peer host for TLS and disabling host and port inference and SNI altogether.
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SniTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfig.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ClientSecurityConfig.java
Labels: API

#1585 Remove Completable publishOnOverride, subscribeOnOverride, publishAndSubscribeOnOverride
  servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/AbstractRequestConcurrencyController.java
  servicetalk-client-api-internal/src/main/java/io/servicetalk/client/api/internal/AbstractReservableRequestConcurrencyController.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/PublishAndSubscribeOnDisableOffloadTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/completable/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnCompletables.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompletableExecutorPreservationTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletablePublishAndSubscribeOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletablePublishOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/CompletableSubscribeOnOverrideTckTest.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ChannelSet.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyConnectionContext.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/PrivilegedListenableAsyncCloseable.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/ChannelSetTest.java
  servicetalk-transport-netty-internal/src/test/java/io/servicetalk/transport/netty/internal/NettyServerContextTest.java
Labels: API, breaking-change

#1621 Remove offload override from Single and Publisher
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/PublishAndSubscribeOnDisableOffloadTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/publisher/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api-internal/src/test/java/io/servicetalk/concurrent/api/single/PublishAndSubscribeOnTest.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnPublishers.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublishAndSubscribeOnSingles.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/SingleExecutorPreservationTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherPublishAndSubscribeOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherPublishAndSubscribeOnTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherPublishOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherSubscribeOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SinglePublishAndSubscribeOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SinglePublishOnOverrideTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/SingleSubscribeOnOverrideTckTest.java
Labels: API, breaking-change

#1602 Remove deprecated `idleTimeout()` methods
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Completable.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Labels: API, breaking-change

#1617 Disable offloading for `NettyConnectionContext#transportError()`
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyConnectionContext.java
Labels: breaking-change

#1551 Revert "Restore public API changes for `grpc-api` (#1548)"
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
Labels: breaking-change

#1550 Revert "Restore public API changes for `transport-netty-internal` (#1549)"
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
Labels: breaking-change

#1420 Remove deprecated `enableWireLogging` and `enableFrameLogging` overloads
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BaseGrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/KeepAliveTest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseHttpBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BaseSingleAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ProtocolConfigBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/PrematureClosureBeforeResponsePayloadBodyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamObserverTest.java
  servicetalk-opentracing-zipkin-publisher/src/main/java/io/servicetalk/opentracing/zipkin/publisher/reporter/UdpReporter.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/AbstractTcpConfig.java
Labels: breaking-change

#1474 Remove deprecated `SecurityConfigurator` and `Builder.secure()` APIs
  docs/modules/ROOT/pages/performance.adoc
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcClientSecurityConfigurator.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerSecurityConfigurator.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/SingleAddressGrpcClientBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcClientSecurityConfigurator.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerSecurityConfigurator.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerSecurityConfigurator.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/MultiAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/PartitionedHttpClientSecurityConfigurator.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientSecurityConfigurator.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerSecurityConfigurator.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultPartitionedHttpClientSecurityConfigurator.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientSecurityConfigurator.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSecurityConfigurator.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/SecurityConfigurator.java
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ServerSecurityConfigurator.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ClientSecurityConfig.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ReadOnlyClientSecurityConfig.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ReadOnlySecurityConfig.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ReadOnlyServerSecurityConfig.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/ServerSecurityConfig.java
Labels: breaking-change

#1627 Fix PublisherFlatMapSingle's demand handling
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapSingle.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapSingleTest.java
Labels: bug

#1638 Remove `allowPrematureClosureBeforePayloadBody()` that was deprecated in #1475
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H1SpecExceptions.java
Labels: breaking-change

#1637 Remove `disableHostnameVerification()` that was deprecated in #1561
  servicetalk-transport-api/src/main/java/io/servicetalk/transport/api/ClientSslConfigBuilder.java
Labels: breaking-change

#1636 Remove `backlog(int)` server builder option that was deprecated in #1375
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/ReadOnlyTcpServerConfig.java
  servicetalk-tcp-netty-internal/src/main/java/io/servicetalk/tcp/netty/internal/TcpServerConfig.java
Labels: breaking-change

#1537 Remove deprecated compression implementation
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/AbstractContentCodec.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/AbstractZipContentCodec.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/ContentCodec.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/ContentCodecBuilder.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/ContentCodings.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/DefaultContentCodecBuilder.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/DeflateContentCodec.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/GzipContentCodec.java
  servicetalk-encoding-api/src/main/java/io/servicetalk/encoding/api/IdentityContentCodec.java
  servicetalk-encoding-api/src/test/java/io/servicetalk/encoding/api/NoopContentCodec.java
  servicetalk-encoding-netty/src/main/java/io/servicetalk/encoding/netty/NettyChannelContentCodec.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcMessageEncodingTest.java
Labels: breaking-change

#1633 Remove `Verifiers` factory that was deprecated in #1392
  servicetalk-concurrent-api-test/src/main/java/io/servicetalk/concurrent/api/test/Verifiers.java
Labels: breaking-change

#1635 Remove `recoverWith` operators that were deprecated in #1435
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Single.java
Labels: breaking-change

#1626 Handle reentry for n-arity Publisher.from
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/From3Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/FromNPublisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/From2PublisherTest.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/From3PublisherTest.java
Labels: bug
