Repository apple/servicetalk, pull requests merged in 2022-08, with the labels that each got.

#2302 Increase `CompositeClosableTest` timeouts
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/CompositeClosableTest.java
Labels: flaky tests

#2303 Hide use of `sun.misc.Unsafe` from `javac`
  servicetalk-buffer-netty/src/main/java/io/servicetalk/buffer/netty/UnreleasableUnsafeNoZeroingDirectByteBuf.java
  servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent.java
  servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/PlatformDependent0.java
  servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ThrowableUtils.java
  servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/PlatformDependentTest.java
  servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/ThrowableUtilsTest.java
Labels: enhancement, technical debt

#2301 Use `compileJava` `options.release`
  build.gradle
  docs/generation/gradle.properties
  gradle.properties
  servicetalk-buffer-api/build.gradle
  servicetalk-concurrent-jdkflow/build.gradle
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkLibraryPlugin.groovy
Labels: bug

#2312 Upgrade Gradle wrapper 7.5 → 7.5.1
  docs/generation/gradle/wrapper/gradle-wrapper.jar
  docs/generation/gradle/wrapper/gradle-wrapper.properties
  docs/generation/gradlew
  docs/generation/gradlew.bat
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#2317 Null check result of `HttpServerBuilder` supplier
  servicetalk-grpc-netty/src/main/java/io/servicetalk/grpc/netty/DefaultGrpcServerBuilder.java
Labels: enhancement

#2330 Clarify debugging examples with more comments
  servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingClient.java
  servicetalk-examples/grpc/debugging/src/main/java/io/servicetalk/examples/grpc/debugging/DebuggingServer.java
  servicetalk-examples/http/debugging/build.gradle
  servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleClient.java
  servicetalk-examples/http/debugging/src/main/java/io/servicetalk/examples/http/debugging/DebuggingExampleServer.java
  servicetalk-examples/http/debugging/src/main/resources/log4j2.xml
  servicetalk-examples/http/http2/build.gradle
  servicetalk-examples/http/mutual-tls/build.gradle
  servicetalk-examples/http/redirects/build.gradle
Labels: docs

#2311 gRPC request/response context to pass data between gRPC and HTTP layers
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/BlockingStreamingGrpcServerResponse.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientCallFactory.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcClientMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcServiceContext.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExceptionMapperServiceFilter.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcMetadata.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcServiceContext.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcUtils.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/customtransport/Utils.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ProtocolCompatibilityTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/RequestResponseContextTest.java
  servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Generator.java
  servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java
  servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Words.java
Labels: enhancement

#2331 Avoid race when HTTP/1.x request is cancelled at connection level filter
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractStreamingHttpConnection.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ClientParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/H2ParentConnectionContext.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpClient.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ReservableRequestConcurrencyControllers.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/CloseUtils.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionInfoTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/GracefulConnectionClosureHandlingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/H2PriorKnowledgeFeatureParityTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTransportObserverTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerGracefulConnectionClosureHandlingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/TimeoutHttpRequesterFilterTest.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/DefaultNettyConnection.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/NettyChannelListenableAsyncCloseable.java
Labels: bug
