Repository apple/servicetalk, pull requests merged in 2022-03, with the labels that each got.

#2108 Remove special `defaultStrategy()` merge method
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/DefaultGrpcExecutionStrategy.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ErrorHandlingTest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ConnectAndHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/DefaultHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingStreamingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToHttpClient.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategiesTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategyTest.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/StrategyInfluencerChainBuilderTest.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractNettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ConnectionCloseHeaderHandlingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/TimeoutFromRequest.java
Labels: technical debt

#2134 Conditionally use ioExecutor timer for retry
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/RedoWhenPublisher.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/LoadBalancerReadyHttpClientTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
Labels: bug

#2133 Deprecate `offloadNever()`
  servicetalk-concurrent-api/src/testFixtures/java/io/servicetalk/concurrent/api/ExecutorExtension.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcExecutionStrategies.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRouter.java
  servicetalk-grpc-api/src/main/java/io/servicetalk/grpc/api/GrpcRoutes.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/ExecutionStrategyTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientRequiresTrailersTest.java
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcClientValidatesContentTypeTest.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategies.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SpecialHttpExecutionStrategy.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/ClientStrategyInfluencerChainBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/NettyHttpServer.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractEchoServerBasedHttpRequesterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/AbstractHttpServiceAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthStrategyInfluencerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/DefaultMultiAddressUrlHttpClientBuilderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOnServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/FlushStrategyOverrideTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpAuthConnectionFactoryClientTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientAsyncContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientBuilderTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpClientOverrideOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpConnectionEmptyPayloadTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpStreamingClientOverrideOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpTestExecutionStrategy.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/MalformedDataAfterHttpMessageTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerConnectionTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/NettyHttpServerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ProxyConnectConnectionFactoryFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerEffectiveStrategyTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerGracefulConnectionClosureHandlingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ServerRespondsOnClosingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/StreamingHttpServiceAsyncContextTest.java
  servicetalk-http-router-jersey/src/main/java/io/servicetalk/http/router/jersey/JerseyRouteExecutionStrategyUtils.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/AbstractResourceTest.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/ExecutionStrategyTest.java
  servicetalk-http-router-jersey/src/testFixtures/java/io/servicetalk/http/router/jersey/MixedModeResourceTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/HttpServerOverrideOffloadingTest.java
  servicetalk-http-router-predicate/src/test/java/io/servicetalk/http/router/predicate/PredicateRouterOffloadingTest.java
Labels: technical debt

#2154 Extend `DefaultHttpExecutionStrategyTest`
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/DefaultHttpExecutionStrategyTest.java
Labels: flaky tests

#2039 Update offloading documentation
  docs/modules/ROOT/pages/blocking-safe-by-default.adoc
  docs/modules/ROOT/pages/performance.adoc
  docs/modules/ROOT/pages/programming-paradigms.adoc
  servicetalk-concurrent-api/docs/modules/ROOT/assets/images/blocking-scenarios.png
  servicetalk-concurrent-api/docs/modules/ROOT/assets/images/blocking-scenarios.svg
  servicetalk-concurrent-api/docs/modules/ROOT/assets/images/executor-thread-selection.png
  servicetalk-concurrent-api/docs/modules/ROOT/assets/images/offloading.svg
  servicetalk-concurrent-api/docs/modules/ROOT/pages/_partials/nav-versioned.adoc
  servicetalk-concurrent-api/docs/modules/ROOT/pages/blocking-implementation.adoc
  servicetalk-concurrent-api/docs/modules/ROOT/pages/blocking-safe-by-default.adoc
  servicetalk-concurrent-api/docs/modules/ROOT/pages/pitfalls.adoc
  servicetalk-concurrent-api/gradle/checkstyle/suppressions.xml
Labels: docs

#2151 Add Publisher.flatMapConcatSingle
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/Publisher.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/PublisherFlatMapConcatUtils.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherFlatMapConcatSingleTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapConcatSingleDelayErrorTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapConcatSingleTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeSingleDelayErrorTckTest.java
  servicetalk-concurrent-reactivestreams/src/test/java/io/servicetalk/concurrent/reactivestreams/tck/PublisherFlatMapMergeSingleTckTest.java
Labels: enhancement, API

#2148 Processors.newPublisherProcessor simplify duplicate terminal check
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/AbstractPublisherProcessorSignalsHolder.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/DefaultBlockingProcessorSignalsHolder.java
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/ProcessorBufferUtils.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/PublisherProcessorTest.java
Labels: performance

#2158 Update spotbugs 4.4.1 -> 4.6.0
  gradle.properties
  servicetalk-concurrent-api/gradle/spotbugs/main-exclusions.xml
  servicetalk-gradle-plugin-internal/plugin-config.gradle
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/Versions.groovy
  servicetalk-grpc-netty/gradle/spotbugs/test-exclusions.xml
  servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/ReflectionUtils.java
Labels: technical debt

#2157 servicetalk-grpc-protoc name conflict fixes
  servicetalk-grpc-protoc/gradle/checkstyle/suppressions.xml
  servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/FileDescriptor.java
  servicetalk-grpc-protoc/src/main/java/io/servicetalk/grpc/protoc/Types.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictEnum.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictMessage.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictMultiService.java
  servicetalk-grpc-protoc/src/test/java/io/servicetalk/grpc/protoc/TestConflictService.java
  servicetalk-grpc-protoc/src/test/proto/test_conflict_enum.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_enum2.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_enum3.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_enum_inside.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_message.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_message2.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_message3.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_service2.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_service3.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_service4.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_service5.proto
  servicetalk-grpc-protoc/src/test/proto/test_conflict_service_outer_class.proto
Labels: bug

#2161 Publisher.multicast duplicate cancel IndexOutOfBounds exception
  servicetalk-concurrent-api/src/main/java/io/servicetalk/concurrent/api/MulticastPublisher.java
  servicetalk-concurrent-api/src/test/java/io/servicetalk/concurrent/api/MulticastPublisherTest.java
Labels: bug

#2156 Use filter strategy for streaming async server
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultHttpServerBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/BasicAuthStrategyInfluencerTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ExecutionStrategyInContextTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpOffloadingTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/SslAndNonSslConnectionsTest.java
Labels: bug

#2153 CONTRIBUTING - Documentation Requirements section
  CONTRIBUTING.adoc
Labels: docs

#2163 Update gradlew 7.3 -> 7.4.1
  docs/generation/gradle.properties
  docs/generation/gradle/validateSite.gradle
  docs/generation/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: technical debt
