Repository apple/servicetalk, pull requests merged in 2022-07, with the labels that each got.

#2268 Upgrade Netty 4.1.78.FINAL → 4.1.79.FINAL
  gradle.properties
Labels: dependencies

#2270 Upgrade Jackson 2.12.2.2 → 2.12.3
  gradle.properties
Labels: dependencies

#2269 Upgrade Log4J 2.17.2 → 2.18.0
  gradle.properties
Labels: dependencies

#2271 Grpc upgrade
  gradle.properties
Labels: dependencies

#2274 `LoadBalancedStreamingHttpConnection` doesn't need connect strategy
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/AbstractLBHttpConnectionFactory.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/LoadBalancedStreamingHttpConnection.java
Labels: bug

#2277 Upgrade Gradle wrapper 7.4.2 → 7.5
  docs/generation/gradle/wrapper/gradle-wrapper.jar
  docs/generation/gradle/wrapper/gradle-wrapper.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#2279 Do not update user's upstream branch
  scripts/release.sh
Labels: bug

#2286 Add `.p12` stores for tests which require format
  servicetalk-test-resources/src/main/java/io/servicetalk/test/resources/DefaultTestCerts.java
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/client_ca.pem
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/generate-certs.sh
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_client.key
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_client.p12
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_client.pem
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_server.key
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_server.p12
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/localhost_server.pem
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/server_ca.pem
  servicetalk-test-resources/src/main/resources/io/servicetalk/test/resources/truststore.p12
  servicetalk-test-resources/src/test/java/io/servicetalk/test/resources/DefaultTestCertsTest.java
Labels: enhancement

#2140 grpc-protoc javadoc testing updates
  servicetalk-grpc-protoc/build.gradle
Labels: bug, docs

#2272 Upgrade JMH 1.3.3 → 1.3.5
  gradle.properties
Labels: dependencies
