Repository apple/servicetalk, pull requests merged in 2022-05, with the labels that each got.

#2202 Generate JavaDoc only for API JavaDoc tasks
  servicetalk-gradle-plugin-internal/src/main/groovy/io/servicetalk/gradle/plugin/internal/ServiceTalkRootPlugin.groovy
Labels: bug, docs

#2209 Tighter dependency for protoc plugin
  servicetalk-grpc-protoc/build.gradle
Labels: enhancement

#2216 Add unit test for gRPC over h1, negotiated by TLS+ALPN
  servicetalk-grpc-netty/src/test/java/io/servicetalk/grpc/netty/GrpcOverH1.java
Labels: docs

#2220 Clear async-context inside RRLB health checking
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
Labels: bug

#2212 Make `HostHeaderHttpRequesterFilter` public
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HeaderUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/SingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClientConfig.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HostHeaderHttpRequesterFilterTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RedirectingClientAndConnectionFilterTest.java
  servicetalk-http-utils/src/main/java/io/servicetalk/http/utils/HostHeaderHttpRequesterFilter.java
  servicetalk-transport-netty-internal/src/main/java/io/servicetalk/transport/netty/internal/BuilderUtils.java
  servicetalk-utils-internal/src/main/java/io/servicetalk/utils/internal/NetworkUtils.java
  servicetalk-utils-internal/src/test/java/io/servicetalk/utils/internal/NetworkUtilsTest.java
Labels: enhancement

#2185 Shared BlockingUtils in concurrent api internal
  servicetalk-concurrent-api-internal/src/main/java/io/servicetalk/concurrent/api/internal/BlockingUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingRequestUtils.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/BlockingToStreamingService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpServerBuilder.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpClientToBlockingStreamingHttpClient.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingHttpConnection.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpConnectionToBlockingStreamingHttpConnection.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToBlockingHttpService.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StreamingHttpServiceToBlockingStreamingHttpService.java
Labels: enhancement

#2219 Use `servicetalk-dependencies` for tests
  servicetalk-concurrent-api/build.gradle
  servicetalk-concurrent-internal/build.gradle
  servicetalk-concurrent-reactivestreams/build.gradle
  servicetalk-http-api/build.gradle
  servicetalk-http-netty/build.gradle
  servicetalk-http-router-jersey/build.gradle
  servicetalk-log4j2-mdc-utils/build.gradle
  servicetalk-opentracing-asynccontext/build.gradle
  servicetalk-opentracing-http/build.gradle
  servicetalk-opentracing-log4j2/build.gradle
  servicetalk-serializer-utils/build.gradle
  servicetalk-tcp-netty-internal/build.gradle
  servicetalk-transport-netty-internal/build.gradle
Labels: technical debt

#2227 Additional test of expected server offloading
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/HttpServerDefaultExecutionStrategyTest.java
Labels: enhancement
