Repository apple/servicetalk, pull requests merged in 2022-01, with the labels that each got.

#2041 Fix infinite retries under particular conditions
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StrategyInfluencerAwareConversions.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Labels: bug

#2043 [BACKPORT] Fix infinite retries under particular conditions (#2041)
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/StrategyInfluencerAwareConversions.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterAutoRetryStrategiesTest.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Labels: bug, Backport

#2042 Allow using pre-existing `AutoRetryStrategyProvider` and `RetryingHttpRequesterFilter`
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Labels: bug

#2044 `RoundRobinLoadBalancer`: make `targetResource` logging less confusing
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancer.java
  servicetalk-loadbalancer/src/main/java/io/servicetalk/loadbalancer/RoundRobinLoadBalancerFactory.java
Labels: enhancement

#2049 [BACKPORT] Fix infinite retries under particular conditions (#2041)
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/ContextAwareStreamingHttpClientFilterFactory.java
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/StrategyInfluencerAwareConversions.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/DefaultSingleAddressHttpClientBuilder.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/HttpClients.java
  servicetalk-http-netty/src/main/java/io/servicetalk/http/netty/RetryingHttpRequesterFilter.java
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/RetryingHttpRequesterFilterTest.java
Labels: bug

#2058 Default `requiredOffloads` use `influenceStrategy`
  servicetalk-http-api/src/main/java/io/servicetalk/http/api/HttpExecutionStrategyInfluencer.java
  servicetalk-http-api/src/test/java/io/servicetalk/http/api/HttpExecutionStrategyTest.java
Labels: bug

#2059 Update Jersey Router documentation
  servicetalk-http-router-jersey/docs/modules/ROOT/pages/index.adoc
Labels: docs

#2062 Fix ClientClosureRaceTest bring back max-retries
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java
Labels: bug

#2061 [Backport] Fix ClientClosureRaceTest bring back max-retries
  servicetalk-http-netty/src/test/java/io/servicetalk/http/netty/ClientClosureRaceTest.java
Labels: bug

#2063 Fix jackson-jersey references to deprecated classes
  servicetalk-data-jackson-jersey/docs/modules/ROOT/pages/index.adoc
Labels: docs
